#ifndef __SBIT_H__
#define __SBIT_H__
#include <mach/mcu51.h>

DEFINE_SBIT(ENCODER_A, P3_INITVAL, 2);
DEFINE_SBIT(ENCODER_B, P1_INITVAL, 4);
DEFINE_SBIT(ENCODER_D, P3_INITVAL, 3);

DEFINE_SBIT(hundreds_place, P3_INITVAL, 4);
DEFINE_SBIT(tens_place, P3_INITVAL, 5);
DEFINE_SBIT(ones_place, P3_INITVAL, 6);

DEFINE_SBIT(T12_SWITCH, P2_INITVAL, 0);

DEFINE_SBIT(BUZZ, P1_INITVAL, 7);

DEFINE_SBIT(HIBER_STATE, P0_INITVAL, 1);

DEFINE_SBIT(DPY_DP, P2_INITVAL, 7);
DEFINE_SBIT(DPY_G, P2_INITVAL, 6);
DEFINE_SBIT(DPY_F, P2_INITVAL, 5);
DEFINE_SBIT(DPY_E,	P2_INITVAL, 4);
DEFINE_SBIT(DPY_D, P2_INITVAL, 3);
DEFINE_SBIT(DPY_C, P2_INITVAL, 2);
DEFINE_SBIT(DPY_B, P2_INITVAL, 1);
DEFINE_SBIT(DPY_A, P3_INITVAL, 7);

#endif